id: P004512
initial_creation_type: ocr
created_at: 29/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W1KG1888
  title: འཇམ་དཔལ་མཚན་བརྗོད་རྩ་འགྲེལ
  author: ''
  volumes:
    89c10faf24344147aa7ca706d044a011:
      image_group_id: I1KG1890
      title: ''
      volume_number: 1
      total_pages: 170
      base_file: v001.txt
